FROM maven:3.8.5-openjdk-17 AS build
COPY . . 
RUN mvn clean package -DskipTests

FROM openjdk:17.01-jdk-slim
COPY --from=build /target/coffee-shop-telegram-bot-0.0.1-SNAPSHOT.jar  coffee-shop-telegram-bot.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","coffee-shop-telegram-bot.jar"]